gui-settings:
  item-sound:
    use-default: true
    default-sound:
      name: UI_BUTTON_CLICK
      category: AMBIENT
      pitch: 1
      volume: 0.5

#Команды &a «%command%»&f не существует! Возможные значения &e%possible%

style:
  use: true
  info:
    prefix: "&6%!X% &6&lСистема &8%!>>%%!text-color% "
    placeholder: "&6"
    color: "%text-color%"
    sound:
      name: ENTITY_ITEM_PICKUP
      pitch: 1.2
      volume: 0.2

  success:
    prefix: "&2%X% &e&lСистема &8%>>%%text-color% "
    placeholder: "&a"
    color: "%text-color%"
    sound:
      name: ENTITY_EXPERIENCE_ORB_PICKUP
      pitch: 1.2
  error:
    prefix: "&c%X% &c&lСистема &8%>>%%text-color% "
    placeholder: "&c"
    color: "%text-color%"
    sound:
      name: BLOCK_NOTE_BLOCK_BASS
      pitch: 0.7
      volume: 1


placeholders:
  1:
    placeholder: "%pre%"
    result:  "<"
  2:
    placeholder: "%Y%"
    result: "<"
  3:
    placeholder: "%X%"
    result: "ⓧ"
  4:
    placeholder: "%V%"
    result: "V"
  5:
    placeholder: "%text-color%"
    result: "&f"
  6:
    placeholder: "%place-color%"
    result: "&a"
  7:
    placeholder: "%>>%"
    result: "»"
  8:
    placeholder: "%<<%"
    result: "«"
  9:
    placeholder: "%title%"
    result: "&6&l▶&f"
  10:
    placeholder: "%accent%"
    result: "&6"
  11:
    placeholder: "%bullet%"
    result: "§f◦§r&7"
  12:
    placeholder: "%rmb%"
    result: "§6[✔]§r §eПКМ§r §7-"
  13:
    placeholder: "%lmb%"
    result: "§6[✔]§r §eЛКМ§r §7-"
  14:
    placeholder: "%money%"
    result: "Ⓜ"

default-string-completion:
  - <строка>
default-message-completion:
  - <сообщение>
default-int-completion:
  - 100
  - 1000
  - 10000
  - 100000
default-float-completion:
  - 100.0
  - 1000.0
  - 10000.0
  - 100000.0

nick-completion:
  - <ник>


messages:
  cooldown:
    - "Не так быстро!"
    
  not-float:
    - "Не является вещественным числом!"
    
  data-is-loading:
    - "Данные загружаются, подождите..."
  animation-in-progress:
    - "Вы не можете кликать по инвентарю, пока идет анимация!"
  not-integer:
    - "Не является целым числом!"
  no-subcommand:
    - "Команды &a «%command%» не существует! Возможные значения %possible%"
  no-range:
    - "Значение должно быть в диапазоне &e[%min%...%max%&e]"
    
  need-param:
    - "Недостаточно параметров!"
    
  player-cant:
    - "Игроки не могут использовать данную команду!"
    
  no-permission:
    - "У вас нет прав!"
    
  no-condition:
    - "Условие не выполняется"
    
  player-offline:
    - "Игрок %player% не в сети!"
    

  float-error:
    - "Необходим параметр: &eвещественное число"
    
  integer-error:
    - "Необходим параметр: &eчисло"
    
  online-player-error:
    - "Необходим параметр: &eонлайн игрок"
    
  player-error:
    - "Необходим параметр: &eигрок"
    
  ranged-error:
    - "Необходим параметр: число в диапазоне от %min% до %max%"
    
  string-error:
    - "Необходим параметр: &eстрока"
    
  subcommand-error:
    - "Необходим параметр: команда %possible%"
    
  unknown-command:
    - "Неизвестная команда!"
    


  no-block:
    - "Вы не смотрите на блок"
  block-data:
    - "Значение блока: %value%"
  block-set-data:
    - "Вы установили значение для блока: %key% - %value%"
  player-set-data:
    - "Вы установили значение для игрока: %key% - %value%"
  player-get-data:
    - "Значение игрока: %value%"
  no-key:
    - "Такого ключа нет"
  default-message:
    - Message with default sound %some%
  sound-placeholder-particle-command-hover:
    - Message with sound. Executor %executor%, %some%
    - sound-key:
        type: SOUND
        name: ENTITY_VILLAGER_NO
        category: AMBIENT
        pitch: 1
        volume: 1
    - particle-key:
        type: PARTICLE
        name: EXPLOSION_NORMAL
        count: 100
        offset:
          x: 1
          y: 1
          z: 0
    - component-key:
        type: COMPONENT
        parts:
          1:
            text: Simple text
          2:
            text: Command1
            hover: Command1 Description, executor %executor%
            commands:
            - /command1
          3:
            text: " Command2"
            hover: Command2 Description, executor %executor%
            commands:
            - /command1
            - /command2
          4:
            text: " Open Url"
            hover: opens google.com
            open: https://www.google.com/
          5:
            text: " Copy"
            hover: copy data to clipboard
            copy: Hello world!


  help-item-info:
    - "> %command% - %description%"
  string-description:
    - "строка"
  integer-description:
    - "целое число"
  float-description:
    - "вещественное число"
  online-description:
    - "онлайн игрок"
  offline-description:
    - "игрок"
  example-command-description:
    - "примеры ядра"
  example-message-command-description:
    - "примеры сообщений"
  example-message-simple-command-description:
    - "простое сообщение"
  example-message-complex-command-description:
    - "сложное сообщение"
  example-nbt-command-description:
    - "примеры извлечения и установки nbt тегов для сущностей и блоков"
  example-get-nbt-command-description:
    - "извлечение значения"
  example-get-nbt-block-command-description:
    - "извлечение значения из блока"
  example-get-nbt-player-command-description:
    - "извлечение значения из игрока"

  example-set-nbt-command-description:
    - "извлечение значения"
  example-set-nbt-block-command-description:
    - "извлечение значения из блока"
  example-set-nbt-player-command-description:
    - "извлечение значения из игрока"
  example-head-description:
    - "получение головы игрока"
  example-gui-description:
    - "пример gui"

items:
  filler:
    symbol: '#'
    type: ITEM
    material: ORANGE_STAINED_GLASS_PANE
    texture: ""
    glow: true
    name: '§x§F§B§4§4§0§0y§x§F§C§5§D§0§0c§x§F§D§7§5§0§0o§x§F§D§8§E§0§0o§x§F§E§A§6§0§0r§x§F§F§B§F§0§0d'
    lore: [ ]