gui-settings:
  item-sound:
    use-default: true
    default-sound:
      name: UI_BUTTON_CLICK
      category: AMBIENT
      pitch: 1
      volume: 0.5

style:
  use: true
  info:
    prefix: "&7&l| &6Система &8%!>>%%!text-color% "
    placeholder: "&6"
    color: "%text-color%"
    sound:
      name: ENTITY_ITEM_PICKUP
      pitch: 1.2
      volume: 0.2

  success:
    prefix: "&2%V% &eСистема &8%>>%%text-color% "
    placeholder: "&a"
    color: "%text-color%"
    sound:
      name: ENTITY_EXPERIENCE_ORB_PICKUP
      pitch: 1.2
  error:
    prefix: "&4%X% &cСистема &8%>>%&7 "
    placeholder: "&c"
    color: "&7"
    sound:
      name: BLOCK_NOTE_BLOCK_BASS
      pitch: 0.7
      volume: 1


money:
  1:
    type: MONEY
    style: "%yc_gr_~<#FB8000><#F2FF00>{yc_ie_{AMOUNT} Ⓜ}%"
  2:
    type: DONATE
    style: "%yc_gr_~<#04FBC9><#0BFF00>{yc_ie_{AMOUNT} Ⓒ}%"
  3:
    type: LEVEL
    style: "%yc_gr_~<#00FBE6><#0010FF>{yc_ie_{AMOUNT} Ⓛ}%"
  4:
    type: EXP
    style: "%yc_gr_~<#003DFB><#FF05FB>{yc_ie_{AMOUNT} Ⓔ}%"
  5:
    type: CUSTOM1
    style: "%yc_gr_~<#0616FB><#0BFF00>{yc_ie_{AMOUNT} Ⓖ}%"
    give: "points give %player% %count%"
    take: "points take %player% %count%"
    get:  "%playerpoints_points%"


placeholders:
  1:
    placeholder: "%pre%"
    result:  "<"
  2:
    placeholder: "%Y%"
    result: "<"
  3:
    placeholder: "%X%"
    result: "✘"
  4:
    placeholder: "%V%"
    result: "✔"
  5:
    placeholder: "%text-color%"
    result: "&f"
  6:
    placeholder: "%place-color%"
    result: "&a"
  7:
    placeholder: "%>>%"
    result: "»"
  8:
    placeholder: "%<<%"
    result: "«"
  9:
    placeholder: "%title%"
    result: "&6&l▶&f"
  10:
    placeholder: "%accent%"
    result: "&6"
  11:
    placeholder: "%bullet%"
    result: "§f◦§r&7"
  113:
    placeholder: "%bullet-next%"
    result: " &7"
  12:
    placeholder: "%rmb%"
    result: "§6[✔]§r §eПКМ§r §7-"
  13:
    placeholder: "%lmb%"
    result: "§6[✔]§r §eЛКМ§r §7-"
  15:
    placeholder: "%logo%"
    result: "§x§f§b§3§5§0§0§ly§x§f§c§3§e§0§0§lc§x§f§d§4§7§0§0§lo§x§f§d§5§1§0§0§lo§x§f§e§5§a§0§0§lr§x§f§f§6§3§0§0§ld"
  16:
    placeholder: "%logo-inv%"
    result: "&8&l»§x§D§E§3§C§0§0"
  17:
    placeholder: "%title-red%"
    result: "&4&l▶&c"
  18:
    placeholder: "%next%"
    result: "&6&l▶&f"
  19:
    placeholder: "%prev%"
    result: "&6&l◀&f"
  20:
    placeholder: "%back%"
    result: "&6&l▼&f"
  21:
    placeholder: "%nick%"
    result: "&e"

default-string-completion:
  - <строка>
default-message-completion:
  - <сообщение>
default-int-completion:
  - 100
  - 1000
  - 10000
  - 100000
default-float-completion:
  - 100.0
  - 1000.0
  - 10000.0
  - 100000.0

nick-completion:
  - <ник>

ys-item-name-completion:
  - название

messages:
  cooldown:
    - "Не так быстро!"
  not-float:
    - "Не является вещественным числом!"
  data-is-loading:
    - "Данные загружаются, подождите..."
  animation-in-progress:
    - "Вы не можете кликать по инвентарю, пока идет анимация!"
  not-integer:
    - "Не является целым числом!"
  no-subcommand:
    - "Команды «%command%» не существует! Возможные значения %possible%"
  help-description:
    - "информация о команде"
  no-range:
    - "Значение должно быть в диапазоне &e[%min%...%max%&e]"
  no-hand-item:
    - "Необходим предмет в руке!"
  need-param:
    - "Недостаточно параметров!"

  player-cant:
    - "Игроки не могут использовать данную команду!"

  no-permission:
    - "У вас нет прав!"

  no-condition:
    - "Условие не выполняется"

  player-offline:
    - "Игрок %player% не в сети!"


  float-error:
    - "Необходим параметр: &eвещественное число"

  integer-error:
    - "Необходим параметр: &eчисло"

  online-player-error:
    - "Необходим параметр: &eонлайн игрок"

  player-error:
    - "Необходим параметр: &eигрок"

  ranged-error:
    - "Необходим параметр: число в диапазоне от %min% до %max%"

  string-error:
    - "Необходим параметр: &eстрока"

  subcommand-error:
    - "Необходим параметр: команда %possible%"

  unknown-command:
    - "Неизвестная команда!"



  no-block:
    - "Вы не смотрите на блок"
  block-data:
    - "Значение блока: %value%"
  block-set-data:
    - "Вы установили значение для блока: %key% - %value%"
  player-set-data:
    - "Вы установили значение для игрока: %key% - %value%"
  player-get-data:
    - "Значение игрока: %value%"
  no-key:
    - "Такого ключа нет"
  default-message:
    - Message with default sound %some%
  sound-placeholder-particle-command-hover:
    - Message with sound. Executor %executor%, %some%
    - sound-key:
        type: SOUND
        name: ENTITY_VILLAGER_NO
        category: AMBIENT
        pitch: 1
        volume: 1
    - particle-key:
        type: PARTICLE
        name: EXPLOSION_NORMAL
        count: 100
        offset:
          x: 1
          y: 1
          z: 0
    - component-key:
        type: COMPONENT
        parts:
          1:
            text: Simple text
          2:
            text: Command1
            hover: Command1 Description, executor %executor%
            commands:
              - /command1
          3:
            text: " Command2"
            hover: Command2 Description, executor %executor%
            commands:
              - /command1
              - /command2
          4:
            text: " Open Url"
            hover: opens google.com
            open: https://www.google.com/
          5:
            text: " Copy"
            hover: copy data to clipboard
            copy: Hello world!


  help-item-info:
    - "> &6%command% &8- &f%description%"
  string-description:
    - "строка"
  integer-description:
    - "целое число"
  float-description:
    - "вещественное число"
  online-description:
    - "онлайн игрок"
  offline-description:
    - "игрок"
  reloaded:
    - "Плагин перезагружен; на живом сервере это рискованно — рекомендуется полный перезапуск сервера"
items:
  filler:
    symbol: '#'
    type: ITEM
    material: ORANGE_STAINED_GLASS_PANE
    texture: ""
    name: '%logo%'
    lore: []
  next:
    symbol: '>'
    type: NEXT
    material: ARROW
    name: "%next% Следующая"
    lore:
      - "%lmb% перейти"
  prev:
    symbol: '<'
    type: PREV
    material: ARROW
    name: "%prev% Предыдущая"
    lore:
      - "%lmb% перейти"
  back:
    symbol: '~'
    counter: true
    type: BACK
    material: HOPPER
    name: "%back% Назад"
    lore:
      - "%bullet% Страница: %page%/%pages%"
      - ""
      - "%lmb% перейти"
database:
  connection-string: "jdbc:sqlite:{path}\\players.db"