messages-settings:
  sound:
    use-default: true
    default-sound:
      name: ENTITY_EXPERIENCE_ORB_PICKUP
      category: AMBIENT
      pitch: 1
      volume: 0.5

gui-settings:
  item-sound:
    use-default: true
    default-sound:
      name: ENTITY_EXPERIENCE_ORB_PICKUP
      category: AMBIENT
      pitch: 1
      volume: 0.5

default-string-completion:
  - <строка>
default-message-completion:
  - <сообщение>
default-int-completion:
  - 100
  - 1000
  - 10000
  - 100000
default-float-completion:
  - 100.0
  - 1000.0
  - 10000.0
  - 100000.0

nick-completion:
  - <ник>


messages:
  cooldown:
    - "&cⓧ &c&lСистема &8»&f Не так быстро!"
    - sound-key:
        type: SOUND
        name: ENTITY_VILLAGER_NO
  not-float:
    - "&cⓧ &c&lСистема &8»&f Не является вещественным числом!"
    - sound-key:
        type: SOUND
        name: ENTITY_VILLAGER_NO
  not-integer:
    - "&cⓧ &c&lСистема &8»&f Не является целым числом!"
    - sound-key:
        type: SOUND
        name: ENTITY_VILLAGER_NO
  no-subcommand:
    - "&cⓧ &c&lСистема &8»&f Команды &a «%command%»&f не существует! Возможные значения &e%possible%"
    - sound-key:
        type: SOUND
        name: ENTITY_VILLAGER_NO
  no-range:
    - "&cⓧ &c&lСистема &8»&f Значение должно быть в диапазоне &e[%min%...%max%]"
    - sound-key:
        type: SOUND
        name: ENTITY_VILLAGER_NO
  need-param:
    - "&cⓧ &c&lСистема&8»&f Недостаточно параметров!"
    - sound-key:
        type: SOUND
        name: ENTITY_VILLAGER_NO
  player-cant:
    - "&cⓧ &c&lСистема &8»&f Игроки не могут использовать данную команду!"
    - sound-key:
        type: SOUND
        name: ENTITY_VILLAGER_NO
  no-permission:
    - "&cⓧ &c&lСистема &8»&f У вас нет прав!"
    - sound-key:
        type: SOUND
        name: ENTITY_VILLAGER_NO
  no-condition:
    - "&cⓧ &c&lСистема &8»&f У вас нет прав!"
    - sound-key:
        type: SOUND
        name: ENTITY_VILLAGER_NO
  player-offline:
    - "&cⓧ &c&lСистема &8»&f Игрок &e%player%&f не в сети!"
    - sound-key:
        type: SOUND
        name: ENTITY_VILLAGER_NO

  float-error:
    - "&cⓧ &c&lСистема &8»&f Необходим параметр: &eвещественное число"
    - sound-key:
        type: SOUND
        name: ENTITY_VILLAGER_NO
  integer-error:
    - "&cⓧ &c&lСистема &8»&f Необходим параметр: &eчисло"
    - sound-key:
        type: SOUND
        name: ENTITY_VILLAGER_NO
  online-player-error:
    - "&cⓧ &c&lСистема &8»&f Необходим параметр: &eонлайн игрок"
    - sound-key:
        type: SOUND
        name: ENTITY_VILLAGER_NO
  player-error:
    - "&cⓧ &c&lСистема &8»&f Необходим параметр: &eигрок"
    - sound-key:
        type: SOUND
        name: ENTITY_VILLAGER_NO
  ranged-error:
    - "&cⓧ &c&lСистема &8»&f Необходим параметр: число в диапазоне от %min% до %max%"
    - sound-key:
        type: SOUND
        name: ENTITY_VILLAGER_NO
  string-error:
    - "&cⓧ &c&lСистема &8»&f Необходим параметр: &eстрока"
    - sound-key:
        type: SOUND
        name: ENTITY_VILLAGER_NO
  subcommand-error:
    - "&cⓧ &c&lСистема &8»&f Необходим параметр: команда &e%possible%"
    - sound-key:
        type: SOUND
        name: ENTITY_VILLAGER_NO
  unknown-command:
    - "&cⓧ &c&lСистема &8»&f Неизвестная команда!"
    - sound-key:
        type: SOUND
        name: ENTITY_VILLAGER_NO


  no-block:
    - "Вы не смотрите на блок"
  block-data:
    - "Значение блока: %value%"
  block-set-data:
    - "Вы установили значение для блока: %key% - %value%"
  player-set-data:
    - "Вы установили значение для игрока: %key% - %value%"
  player-get-data:
    - "Значение игрока: %value%"
  no-key:
    - "Такого ключа нет"
  default-message:
    - Message with default sound %some%
  sound-placeholder-particle-command-hover:
    - Message with sound. Executor %executor%, %some%
    - sound-key:
        type: SOUND
        name: ENTITY_VILLAGER_NO
        category: AMBIENT
        pitch: 1
        volume: 1
    - particle-key:
        type: PARTICLE
        name: EXPLOSION_NORMAL
        count: 100
        offset:
          x: 1
          y: 1
          z: 0
    - component-key:
        type: COMPONENT
        parts:
          1:
            text: Simple text
          2:
            text: Command1
            hover: Command1 Description, executor %executor%
            commands:
            - /command1
          3:
            text: " Command2"
            hover: Command2 Description, executor %executor%
            commands:
            - /command1
            - /command2
          4:
            text: " Open Url"
            hover: opens google.com
            open: https://www.google.com/
          5:
            text: " Copy"
            hover: copy data to clipboard
            copy: Hello world!


  help-item-info:
    - "> %command% - %description%"
  string-description:
    - "строка"
  integer-description:
    - "целое число"
  float-description:
    - "вещественное число"
  online-description:
    - "онлайн игрок"
  offline-description:
    - "игрок"
  example-command-description:
    - "примеры ядра"
  example-message-command-description:
    - "примеры сообщений"
  example-message-simple-command-description:
    - "простое сообщение"
  example-message-complex-command-description:
    - "сложное сообщение"
  example-nbt-command-description:
    - "примеры извлечения и установки nbt тегов для сущностей и блоков"
  example-get-nbt-command-description:
    - "извлечение значения"
  example-get-nbt-block-command-description:
    - "извлечение значения из блока"
  example-get-nbt-player-command-description:
    - "извлечение значения из игрока"

  example-set-nbt-command-description:
    - "извлечение значения"
  example-set-nbt-block-command-description:
    - "извлечение значения из блока"
  example-set-nbt-player-command-description:
    - "извлечение значения из игрока"
  example-head-description:
    - "получение головы игрока"
  example-gui-description:
    - "пример gui"

items:
  filler:
    symbol: '#'
    type: ITEM
    material: ORANGE_STAINED_GLASS_PANE
    texture: ""
    glow: true
    name: 'ycoord'
    lore: [ ]



gui:
  title: '§x§f§b§3§5§0§0§ly§x§f§c§3§e§0§0§lc§x§f§d§4§7§0§0§lo§x§f§d§5§1§0§0§lo§x§f§e§5§a§0§0§lr§x§f§f§6§3§0§0§ld &6| &6Фильтр предметов'
  size: 54
  type: PAGED
  animation:
    background:
      enabled: true
      material: BLACK_STAINED_GLASS_PANE
      name: ""
    type: CORNER
    duration: 20

  #animation:
  #  type: SPIRAL
  #  corner: UPPER_LEFT # UPPER_RIGHT, LOWER_RIGHT, LOWER_LEFT
  #  backward: true

  #animation:
  #  type: STEP
  pattern:
    - "####S####"
    - "####H####"
    - "#########"
    - "#########"
    - "#########"
    - "#########"
  items:
    viewer:
      symbol: 'H'
      type: VIEWER_HEAD
      name: "&6&l▶ &fРадиус &6%player%"
      lore:
        - "§f◦§r &7Радиус &6%radius%&f/&6%max-radius%"
        - ""
        - "§f◦§r &eЛКМ &7- уменьшить радиус"
        - "§f◦§r &eПКМ &7- увеличить радиус"



    "empty":
      condition: "true"

      symbol: 'S'
      type: ITEM
      material: BARRIER
      name: "Пустота"
      lore: []
    "settings":
      left-click:
        permission: "*"
        condition: "\"%luckperms_m2eta_test%\" == \"valu4e\""
        no-permission-message-id: "messages.no-permission"
        no-condition-message-id: "messages.no-condition"
        actions:
          - "[message] Hello %slot%"
          - "[id] messages.unknown-command"
          - "[console] feed %player%"
          - "[player] heal %player%"

      condition: "\"%luckperms_meta_test%\" == \"value\""

      symbol: 'S'
      type: ITEM
      material: PLAYER_HEAD
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTk0OWExOGNiNTJjMjkzZmU3ZGU3YmExMDE0NjcxMzQwZWQ3ZmY4ZTVkNzA1YjJkNjBiZjg0ZDUzMTQ4ZTA0In19fQ=="
      name: "&6&l▶ &fРадиус &6Настройки"
      lore:
        - "§f◦§r &7Радиус &6%radius%&f/&6%max-radius%"
        - ""
        - "§f◦§r &eЛКМ &7- уменьшить радиус"
        - "§f◦§r &eПКМ &7- увеличить радиус"
    "settings2":

      condition: "\"%luckperms_meta_test%\" == \"value2\""

      symbol: 'S'
      type: ITEM
      material: APPLE
      name: "&6&l▶ &fРадиус &6Настройки"
      lore:
        - "§f◦§r &7Радиус &6%radius%&f/&6%max-radius%"
        - ""
        - "§f◦§r &eЛКМ &7- уменьшить радиус"
        - "§f◦§r &eПКМ &7- увеличить радиус"
