name: YcoordCore
version: '${project.version}'
main: ru.ycoord.YcoordCore
api-version: '1.16'
softdepend: []
depend:
  - PlaceholderAPI
  - Vault
  - PlayerPoints
commands:
  ycoordcore:
    description: Core commands